name: Deploy Full Stack App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🔧 Install Dependencies (Client)
        working-directory: ./client
        run: npm ci

      - name: 🛠 Build Frontend
        working-directory: ./client
        run: npm run build

      - name: 🔧 Install Dependencies (Server)
        working-directory: ./server
        run: npm ci

      # Optional: Run server tests here

      - name: ✅ CI/CD Complete
        run: echo "Code built successfully!"
